export const dailyHeaders = [
  {
    name: 'Technical Indicator',
    help: true,
    tooltip:
      'The technical indicator analyzes past price movement trends to forecast future price direction. For instance, if a particular stock has been rising over the past 15 minutes, we may predict that this upward trend will continue for the next 15 minutes. In this case, buying the stock and holding it for at least 5 minutes would be recommended.',
    bold: true,
  },
  {
    name: 'Note',
    value: 'Lorem',
  },
  {
    name: 'Action',
    color: 'rgba(217, 217, 217, 1)',
    value: 'Lorem',
    help: true,
    tooltip:
      'Consider buying stocks when certain criteria are met—such as when a stock is expected to reach a higher price than its current level, or it hits specific price targets, among other indicators. On the other hand, if these conditions reverse, selling the stock may be recommended; otherwise, holding the stock could be the best choice.',
  },
  {
    name: 'Sector',
    value: 'Lorem',
    color: 'rgba(241, 241, 241, 1)',
  },
  {
    name: 'Index',
    color: 'rgba(217, 217, 217, 1)',
    value: 'NYSE',
  },
  {
    name: 'Stock Name',
    color: 'rgba(255, 247, 5, 1)',
    value: 'IRFC',
    filter_disabled: true,
  },
  {
    name: 'Market Opening Price',
    color: 'rgba(215, 216, 218, 1)',
    value: '$ 242.00',
  },
  {
    name: 'Current Price',
    color: 'rgba(241, 241, 241, 1)',
    value: '$ 242.00',
    filter_disabled: true,
  },
  {
    name: 'Day Chg',
    color: 'rgba(36, 78, 17, 1)',
    textColor: 'white',
    value: '$ 4.25',
  },
  {
    name: 'Day Chg P/L %',
    color: 'rgba(36, 78, 17, 1)',
    textColor: 'white',
    value: '8.254%',
  },
  {
    name: 'Estimated Daily Lowest Change%',
    color: 'rgba(217, 217, 217, 1)',
    value: '8.254%',
    tooltip: '',
  },
  {
    name: 'Estimated Daily Highest Change%',
    color: 'rgba(217, 217, 217, 1)',
    value: '8.254%',
    tooltip: '',
  },
  {
    name: 'Target Daily Profit%',
    color: 'rgba(217, 217, 217, 1)',
    value: '8.254%',
    tooltip: '',
  },
  {
    name: 'Barkerage Commission',
    textColor: 'rgba(37, 6, 255, 1)',
    value: '7.6',
  },
  {
    name: 'Lot',
    textColor: 'rgba(37, 6, 255, 1)',
    value: '55',
  },
  {
    name: 'Total Cost',
    textColor: 'rgba(37, 6, 255, 1)',
    value: '$ 1,200,000',
  },

  {
    name: 'Selling Price Target',
    color: 'rgba(240, 240, 240, 1)',
    textColor: 'rgba(17, 130, 65, 1)',
    value: '$ 18.90',
  },
  {
    name: 'Target Current Profit%',
    color: 'rgba(240, 240, 240, 1)',
    textColor: 'rgba(17, 130, 65, 1)',
    value: '-2.71%',
  },
  {
    name: 'Total Target Profit',
    color: 'rgba(240, 240, 240, 1)',
    textColor: 'rgba(17, 130, 65, 1)',
    value: '$ 0.515',
  },
  {
    name: 'DCF',
    color: 'rgba(217, 217, 217, 1)',
    value: 'Undervalued',
    help: true,
    tooltip: `DCF, or Discounted Cash Flow analysis, is a financial valuation technique that estimates the worth of an investment based on its projected future cash flows. The key concept behind DCF is that an investment's current value is derived from the present value of the cash flows it is expected to produce over time.
    Our DCF calculation provides a preliminary estimate generated by an AI model. We recommend verifying these estimates for accuracy.`,
  },
  {
    name: 'Technical Analysis Score',
    color: 'rgba(217, 217, 217, 1)',
    value: '4,525',
    help: true,
    tooltip: `Technical analysis scores are based on historical price trends, operating on the premise that future movements may align with past patterns, though not guaranteed. These scores are built on principles of trend sustainability, average periodic returns, and a strong correlation with the Sharpe ratio.`,
  },
  {
    name: 'Beta',
    value: '0.2451',
    color: 'rgba(243, 243, 243, 1)',
  },
  {
    name: 'Sharp Ratio (Current Year)',
    value: '5:4',
    color: 'rgba(243, 243, 243, 1)',
    filter_disabled: true,
  },
  {
    name: 'P/E',
    value: '42.215',
    color: 'rgba(243, 243, 243, 1)',
  },
  {
    name: 'Market Cap SIze',
    value: '$ 45,142,142',
    color: 'rgba(243, 243, 243, 1)',
  },
  {
    name: 'Market Capitalization',
    value: '$ 45,142,142',
    color: 'rgba(243, 243, 243, 1)',
  },
  {
    name: 'Previous Day Chg%',
    color: 'rgba(12, 243, 6, 1)',
    textColor: 'white',
    value: 'N/A',
  },
  {
    name: 'Cost Of Information',
    value: '$2',
    color: 'rgba(12, 243, 6, 1)',
    textColor: 'white',
    tooltip:
      'This is a one-time fee for accessing exclusive stock recommendations. By purchasing this information, you gain insights into which stocks are most likely to increase in value soon. Our expert analysis helps you get ahead in the market, giving you the opportunity to invest before prices rise and maximize your potential gains.',
    help: true,
  },
]

export const technicalIndicators = {
  firstHalf: {
    times: ['1 Minute', '5 Minute', '15 Minute'],
    values: ['Buy', 'Strong Buy', 'Neutral'],
  },
  secondHalf: {
    times: ['30 Minute', 'Hourly', 'Daily'],
    values: ['Strong Sell', 'Sell', 'Neutral'],
  },
}
