export const positionHeaders = [
  {
    name: "Momentum",
    help: true,
    filter_disabled: true,
    tooltip: `This section provides the projected earnings call date for the stock listed below.  
Investors might benefit by purchasing the stock early within the momentum range to maximize potential gains while managing their preferred risk.  
Studies indicate that market reactions frequently extend the stock’s price trend in the same direction for several months following the earnings call.

**Note:** Earnings call dates are estimates, and any associated risk with this feature is beyond our responsibility.`,
  },
  {
    name: "Note",
    value: "Hey Mayur",
  },
  {
    name: "Action",
    value: "Success",
    help: true,
    tooltip: `Consider buying stocks when certain criteria are met—such as when a stock is expected to reach a higher price than its current level, or it hits specific price targets, among other indicators. On the other hand, if these conditions reverse, selling the stock may be recommended; otherwise, holding the stock could be the best choice.`,
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Sector",
    value: "Lorem",
  },
  {
    name: "Index",
    value: "NYSE",
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Stock Name",
    value: "IRFC",
    filter_disabled: true,
    color: "rgba(255, 247, 5, 1)",
  },
  {
    name: "Current Price",
    value: "$ 242.00",
    filter_disabled: true,
    color: "rgba(215, 216, 218, 1)",
  },
  {
    name: "Day Chg",
    value: "$ 4.25",
    color: "rgba(36, 78, 17, 1)",
    textColor: "white",
  },
  {
    name: "Day Chg P/L %",
    value: "8.254%",
    color: "rgba(36, 78, 17, 1)",
    textColor: "white",
  },
  {
    name: "Target Buy Price",
    value: "1,100",
    color: "rgba(254, 241, 201, 1)",
  },
  {
    name: "Lot",
    value: "1,500",
    help: true,
    tooltip: `To help us estimate your target total profit, please select your preferred budget allocation for the number of stocks you'd like to purchase through your broker from the options below.

Note: This is for forecasting purposes only.`,
    color: "rgba(248, 228, 203, 1)",
  },
  {
    name: "Total Cost",
    value: "4,500",
    help: true,
    tooltip: "",
    color: "rgba(74, 134, 232, 1)",
    textColor: "white",
  },
  {
    name: "Target Holding Period",
    value: "5 days",
    help: true,
    tooltip: `To help us determine your target profit and selling price, you can choose your preferred holding period from the options below.

Note: This is for forecasting purposes only.`,
    color: "rgba(216, 234, 210, 1)",
  },
  {
    name: "Target Profit%",
    value: "50%",
    color: "rgba(55, 118, 29, 1)",
    textColor: "white",
  },
  {
    name: "Target Profit",
    value: "$ 12,000",
    color: "rgba(55, 118, 29, 1)",
    textColor: "white",
  },
  {
    name: "Target Selling Price",
    value: "$ 12,000",
    color: "rgba(55, 118, 29, 1)",
    textColor: "white",
  },
  {
    name: "DCF",
    value: "Undervalued",
    help: true,
    tooltip: `DCF, or Discounted Cash Flow analysis, is a financial valuation technique that estimates the worth of an investment based on its projected future cash flows. The key concept behind DCF is that an investment's current value is derived from the present value of the cash flows it is expected to produce over time.

Our DCF calculation provides a preliminary estimate generated by an AI model. We recommend verifying these estimates for accuracy.`,
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Technical Analysis Score",
    value: "$ 4,525",
    help: true,
    tooltip: `Technical analysis scores are based on historical price trends, operating on the premise that future movements may align with past patterns, though not guaranteed. These scores are built on principles of trend sustainability, average periodic returns, and a strong correlation with the Sharpe ratio.`,
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Fundamental Analysis Score",
    value: "$ 8,525",
    help: true,
    filter_disabled: true,
    tooltip: "",
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Rank Porfolio",
    value: "5",
    help: true,
    filter_disabled: true,
    tooltip: "",
    color: "rgba(217, 217, 217, 1)",
  },
  {
    name: "Average Long Term Return",
    value: "$ 40,000.00",
    color: "rgba(253, 125, 118, 1)",
    textColor: "white",
  },
  {
    name: "Average Monthly Historical Return",
    value: "$ 20,000.00",
    color: "rgba(253, 125, 118, 1)",
    textColor: "white",
  },
  {
    name: "Average 5 Days Return",
    value: "$ 1,200,000",
    color: "rgba(253, 125, 118, 1)",
    textColor: "white",
  },

  {
    name: "Sharp Ratio (Previous Year)",
    value: "4:2",
    filter_disabled: true,
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "Sharp Ratio (Current Year)",
    value: "5:4",
    filter_disabled: true,
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "Beta",
    value: "0.2451",
    filter_disabled: true,
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "P/E",
    value: "42.215",
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "Market Cap SIze",
    value: "$ 45,142,142",
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "Market Capitalization",
    value: "$ 45,142,142",
    color: "rgba(243, 243, 243, 1)",
  },
  {
    name: "Market's Previous Day Chg%",
    value: "N/A",
    color: "rgba(12, 243, 6, 1)",
    textColor: "white",
  },
  {
    name: "Market's 5 Days Chg%",
    value: "N/A",
    color: "rgba(12, 243, 6, 1)",
    textColor: "white",
  },
  // {
  //   name: 'Hold',
  //   value: '41',
  //   filter_disabled: true,
  // },
  // {
  //   name: 'Purchase Date',
  //   value: '20/02/2024',
  //   filter_disabled: true,
  // },
  // {
  //   name: 'Average Buy Price',
  //   value: 'N/A',
  // },
  // {
  //   name: 'Target Lot',
  //   value: 'N/A',
  // },
  {
    name: "Cost Of Information",
    value: "$2",
    help: true,
    color: "rgba(12, 243, 6, 1)",
    textColor: "white",
  },
];
